### PR TITLE
fix text and title of theme

### PR DESCRIPTION
**Pull request by xiangpin**
fix the text and title of `theme`.

The related issue #24 

```
library(magrittr)
library(ggplot2)
library(ggbreak)
data("cars")

cars %>% ggplot(aes(x = speed)) +
  geom_bar() +
  scale_y_break(c(2,3)) +
  theme(text = element_text(family = "Comic Sans MS", face="bold"))
```
xx

### CODE REVIEW

**Comment by lglip** [comment]
Hi

I've tried:

`remotes::install_github("YuLab-SMU/ggbreak")`

to try the axis.title fix.

However, it throws this error back at me:
`Downloading GitHub repo YuLab-SMU/ggbreak@HEAD
√  checking for file '[...]' (336ms)
preparing 'ggbreak':
√  checking DESCRIPTION meta-information ... 
checking for LF line-endings in source and make files and shell scripts
checking for empty or unneeded directories
building 'ggbreak_0.0.5.992.tar.gz'
   
Installing package into ‘[...]’
(as ‘lib’ is unspecified)
installing *source* package 'ggbreak' ...
using staged installation
R
byte-compile and prepare package for lazy loading
Error in get(x, envir = ns, inherits = FALSE) : 
  object 'is.ggbreak' not found
Error: unable to load R code in package 'ggbreak'
Execution halted
ERROR: lazy loading failed for package 'ggbreak'
removing '[...]'
restoring previous '[...]'
Warning message:
In i.p(...) :
  installation of package ‘[...]/ggbreak_0.0.5.992.tar.gz’ had non-zero exit status`

**Comment by xiangpin** [comment]
I think this might be the issue of the environment. Please try to restart R or Rstudio, then re-install.

**Comment by GuangchuangYu** [comment]
@lglip you need to install `YuLabSMU/aplot` first.

**Comment by lglip** [comment]
Works like a charm now! Thanks!

**Pull request merged**
